backend/controllers/AuthController.php
<?php

namespace backend\controllers;

use common\web\AuthControllerInterface;
use Yii;
use common\web\Controller;
use backend\models\SignInForm;

class AuthController extends Controller implements AuthControllerInterface
{
    /**
     * Logs in a user.
     *
     * @return mixed
     * @throws \yii\base\InvalidParamException
     */
    public function actionSignIn()
    {
        $model = new SignInForm();

        if( $model->load(Yii::$app->request->post()) ) {
            if( $model->login() ) {
                return $this->goBack();
            } else {
                $model->flashError();
            }
        }

        return $this->render('sign-in', [
            'model' => $model,
        ]);
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionSignOut()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/AuthController.php
<?php

namespace frontend\controllers;

use Yii;
use common\web\Controller;
use common\web\AuthControllerInterface;
use frontend\models\SignInForm;
use frontend\models\SignUpForm;

class AuthController extends Controller implements AuthControllerInterface
{
    /**
     * Logs in a user.
     *
     * @return mixed
     * @throws \yii\base\InvalidParamException
     */
    public function actionSignIn()
    {
        $model = new SignInForm();

        if( $model->load(Yii::$app->request->post()) ) {
            if( $model->login() ) {
                return $this->goBack();
            } else {
                $model->flashError();
            }
        }

        return $this->render('sign-in', [
            'model' => $model,
        ]);
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionSignOut()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Signs user up.
     *
     * @return mixed
     * @throws \yii\base\Exception
     * @throws \yii\base\InvalidParamException
     */
    public function actionSignUp()
    {
        $model = new SignUpForm();

        if( $model->load(Yii::$app->request->post()) ) {
            if( $user = $model->signup() ) {
                if( Yii::$app->getUser()->login($user) ) {
                    return $this->goHome();
                }
            } else {
                $model->flashError();
            }
        }

        return $this->render('sign-up', [
            'model' => $model,
        ]);
    }
}

frontend/views/layouts/partial/navigation.php
<?php
/**
 * @var \common\web\View $this
 */

use common\widgets\LanguageSwitcher;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;

if( Yii::$app->getUser()->getIsGuest() ) {
    $menu = [
        LanguageSwitcher::widget(),
        [
            'label' => Yii::t('app', 'Sign up'),
            'url'   => ['/auth/sign-up'],
        ],
        [
            'label' => Yii::t('app', 'Sign in'),
            'url'   => ['/auth/sign-in'],
        ],
    ];
} else {
    $menu = [
        [
            'label' => Yii::t('app', 'Main'),
            'url'   => ['/site/index'],
        ],
        [
            'label' => Yii::t('app', 'About'),
            'url'   => ['/site/about'],
        ],
        [
            'label' => Yii::t('app', 'Contacts'),
            'url'   => ['/site/contact'],
        ],
        LanguageSwitcher::widget(),
        [
            'label'       => Yii::t('app', 'Sign out'),
            'url'         => ['/auth/sign-out'],
            'linkOptions' => ['data-method' => 'post'],
        ],
    ];
}

NavBar::begin([
    'brandLabel' => Yii::$app->name,
    'brandUrl'   => Yii::$app->getHomeUrl(),
    'options'    => [
        'class' => 'navbar-inverse navbar-fixed-top',
    ],
]);

echo Nav::widget([
    'options'      => ['class' => 'navbar-nav navbar-right'],
    'items'        => $menu,
    'encodeLabels' => false,
]);

NavBar::end();